### ISSUE TITLE
With the new UX, hard to find proposals that need review

### ISSUE THREAD

**Issue by chandanworkacct** [dapperlabs/nft-catalog#123]
With new UX, it is hard to find the latest proposals that need review. There are multiple issues with the new UX:
1. Infinite scrolling requires multiple clicks to get to the bottom
2. There is no easy way to discern if there is an updated proposal for a proposal under review.

Suggestions:
1. Add a filter to show only proposals that require review
2. Hide proposals whose updated version has been submitted for review

**Comment by aishairzay** [comment]
Agreed - i'll work on a PR for these.

**Comment by aishairzay** [comment]
This is in now
