### ISSUE TITLE
Can use the proposal Id `0` and update the totalProposals after assigning the catalog proposals

### ISSUE THREAD

**Issue by satyamakgec** [dapperlabs/nft-catalog#14]
Here https://github.com/dapperlabs/nft-catalog/blob/8cb26110e41190316e718bb0797da338f0713662/cadence/contracts/NFTCatalog.cdc#L194

We are not storing anything for proposal id `0`

**Comment by aishairzay** [comment]
Any reason we should start at 0 instead of 1?

IMO it looks nicer and is more readable to start from 1. Also, it might be too late to make this change now that there have been some proposals made in mainnet
