### ISSUE TITLE
Fill in collection identifier

### ISSUE THREAD

**Issue by bjartek** [dapperlabs/nft-catalog#24]
In step 5 of the wizard we are asked to fill inn the collection identifier. Since we have already submitted an NFT that has a collectionDisplay view, can we prefil in the value from the name there? The intent when that view was created was that the name should be an url safe identifier and the description a long form one. (Atleast that was my intent)

**Comment by aishairzay** [comment]
Agreed, this should be helpful for most cases and the collection owner can manually change it if the prefill isn't right, made a PR here: https://github.com/dapperlabs/nft-catalog/pull/27
